require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

# Useful to separate conceptual expressions.
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false

# The default of 5 is VERY ambicious. And there are plenty of cases where we need to
# generate large expectation hashes.
RSpec/ExampleLength:
  Enabled: false

# change(thing, :method) is clever, but it's also magical. Use it, but don't enforce it.
RSpec/ExpectChange:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

# Just one expectation per example is ambitious.
RSpec/MultipleExpectations:
  Max: 5

# %i[foo bar baz] is more difficult to understand than [:foo, :bar, :baz]
Style/SymbolArray:
  Enabled: false

# Use whichever makes sense
Style/AccessModifierDeclarations:
  Enabled: false

# The intent of writing comments in English is noble, but restricting comments to ASCII is not how you do it.
Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: "braces_for_chaining"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# It gets silly with tiny arrays
Style/WordArray:
  MinSize: 4
