require:
  - rubocop-rspec
  - rubocop-performance

# Use whichever makes sense
Style/AccessModifierDeclarations:
  Enabled: false

# The intent of writing comments in English is noble, but restricting comments to ASCII is not how you do it.
Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# It gets silly with tiny arrays
Style/WordArray:
  MinSize: 4
